apiVersion: v1
kind: Service
metadata:
  name: cafe-website-service
  labels:
    app: cafe-website
spec:
  type: LoadBalancer # Use NodePort or ClusterIP if not running in a cloud environment that supports LoadBalancers
  selector:
    app: cafe-website
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP